Update BuffIcons.cs
Added defensive checks in CleanupIcons to return early when the Mobile is null and to safely handle cases where a mobile has no backpack

Ensured buffs are removed appropriately whenever an expected item is absent, preventing null references during buff cleanup

Fix for:
```
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
at Server.BuffInfo.CleanupIcons(Mobile m, Boolean onlyParalyzed) in c:\Confictura-Server\Data\Scripts\System\Misc\BuffIcons.cs:line 249
at Server.Spells.Chivalry.RemoveCurseSpell.RemoveBadThings(Mobile m) in c:\Confictura-Server\Data\Scripts\Magic\Knight\RemoveCurse.cs:line 65
at Server.Spells.Herbalist.HerbalHealingSpell.Target(Mobile m) in c:\Confictura-Server\Data\Scripts\Magic\Druidism\Effects\HerbalHealingSpell.cs:line 73
at Server.Spells.Herbalist.HerbalHealingSpell.InternalTarget.OnTarget(Mobile from, Object o) in c:\Confictura-Server\Data\Scripts\Magic\Druidism\Effects\HerbalHealingSpell.cs:line 93
at Server.Targeting.Target.Invoke(Mobile from, Object targeted) in C:\Confictura-Server-Solution\ConficturaUO\Data\System\Source\Targeting\Target.cs:line 274
at Server.Network.PacketHandlers.TargetResponse(NetState state, PacketReader pvSrc) in C:\Confictura-Server-Solution\ConficturaUO\Data\System\Source\Network\PacketHandlers.cs:line 1254
at Server.Network.MessagePump.HandleReceive(NetState ns) in C:\Confictura-Server-Solution\ConficturaUO\Data\System\Source\Network\MessagePump.cs:line 151
at Server.Network.MessagePump.Slice() in C:\Confictura-Server-Solution\ConficturaUO\Data\System\Source\Network\MessagePump.cs:line 136
at Server.Core.Main(String[] args) in C:\Confictura-Server-Solution\ConficturaUO\Data\System\Source\Main.cs:line 588
```